# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'turnup' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for turnup

  target 'turnup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'turnupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'turnup-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for turnup-tvOS

  target 'turnup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
